/**
 * Fold the WhatsApp "Quadro de Honra" into the second half of
 * `articles/ficheiros-da-francesinha.html`.
 *
 *   node scripts/join-article.mjs
 *
 * The two halves come from different places. The first — everything about the
 * games — is hand-written prose in the article itself. The second is generated
 * from the group's chat archive by `scripts/chatstats/gen.py`, which belongs to
 * that pipeline and is re-run whenever the archive is re-parsed. So this script
 * is idempotent: it replaces the block between the markers below, leaving the
 * hand-written half alone. Re-run it after every `gen.py` run, then re-import
 * with `scripts/import-article.mjs`.
 *
 * The join is a re-skin, not a copy. The chat page is a light, paper-and-pitch
 * design in Bebas Neue and Source Serif 4; the article is a committed dark one
 * in Oswald and Newsreader. One page can only have one identity, so the chat
 * half keeps its layout and loses its palette and typefaces: its custom
 * properties are remapped onto the article's, its two display faces onto the
 * article's two, and its section headers are rebuilt in the article's own
 * `sec-head` pattern so the rhythm carries straight through.
 *
 * Its CSS is scoped to `.qh` *and* every class it defines is renamed `qh-*`,
 * because the two stylesheets both use `.card`, `.big`, `.note`, `.legend`,
 * `.bar`, `.num` and `.hi` for entirely different things. Scoping alone would
 * not be enough: the article's `.card` would still reach a `.qh .card` and add
 * its own padding and background.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const SOURCE = resolve(root, "scripts/chatstats/quadro-de-honra.html");
const ARTICLE = resolve(root, "articles/ficheiros-da-francesinha.html");

const CSS_OPEN = "  /* ── Quadro de Honra ─── generated by scripts/join-article.mjs ── */";
const CSS_CLOSE = "  /* ── end Quadro de Honra ─────────────────────────────────────── */";
const HTML_OPEN =
  "<!-- Quadro de Honra — generated by scripts/join-article.mjs, do not edit here -->";
const HTML_CLOSE = "<!-- end Quadro de Honra -->";

/** Section id → the eyebrow it gets, continuing the article's file numbering. */
const EYEBROWS = {
  ranking: "14 — a tagarelice",
  ritmo: "15 — o pulso",
  palavra: "16 — prémios: a palavra",
  riso: "17 — prémios: o riso",
  relogio: "18 — prémios: o relógio",
  balneario: "19 — prémios: o balneário",
  estilo: "20 — prémios: o estilo",
  dicionario: "21 — o dicionário",
  arquivo: "22 — o arquivo",
  social: "23 — a teia",
};

/** Rules the article already provides; the chat page's versions are dropped. */
const DROP = [
  /^:root/,
  /^\*$/,
  /^body$/,
  /^\.wrap$/,
  /^h1, ?h2, ?h3/,
  /^header\.top/,
  /^\.score/,
  /^\.sec$/,
  /^\.sechead/,
  /^\.eyebrow$/,
  /^footer$/,
];

/* ------------------------------------------------------------------ CSS */

function splitRules(css) {
  const rules = [];
  let depth = 0;
  let start = 0;
  let inComment = false;
  for (let i = 0; i < css.length; i += 1) {
    if (inComment) {
      if (css.startsWith("*/", i)) inComment = false;
      continue;
    }
    if (css.startsWith("/*", i)) {
      inComment = true;
      continue;
    }
    if (css[i] === "{") depth += 1;
    else if (css[i] === "}") {
      depth -= 1;
      if (depth === 0) {
        rules.push(css.slice(start, i + 1));
        start = i + 1;
      }
    }
  }
  return rules;
}

function splitSelectors(selector) {
  const parts = [];
  let depth = 0;
  let start = 0;
  for (let i = 0; i < selector.length; i += 1) {
    const c = selector[i];
    if (c === "(" || c === "[") depth += 1;
    else if (c === ")" || c === "]") depth -= 1;
    else if (c === "," && depth === 0) {
      parts.push(selector.slice(start, i));
      start = i + 1;
    }
  }
  parts.push(selector.slice(start));
  return parts.map((p) => p.trim()).filter(Boolean);
}

/** Every class the chat stylesheet defines, so the markup can be renamed too. */
function classNames(css) {
  const names = new Set();
  for (const match of css.matchAll(/\.(-?[A-Za-z_][\w-]*)/g)) names.add(match[1]);
  return names;
}

function transformCss(css, classes) {
  return splitRules(css)
    .map((rule) => {
      const open = rule.indexOf("{");
      if (open === -1) return "";
      const body = rule.slice(open + 1, rule.lastIndexOf("}"));
      const prelude = rule
        .slice(0, open)
        .replace(/\/\*[\s\S]*?\*\//g, " ")
        .trim();

      if (prelude.startsWith("@media") || prelude.startsWith("@supports")) {
        const inner = transformCss(body, classes);
        return inner.trim() ? `  ${prelude} {\n${inner}\n  }` : "";
      }
      if (prelude.startsWith("@")) return `  ${rule.trim()}`;

      const kept = splitSelectors(prelude).filter(
        (one) => !DROP.some((pattern) => pattern.test(one)),
      );
      if (!kept.length) return "";

      const scoped = kept
        .map((one) =>
          one.replace(/\.(-?[A-Za-z_][\w-]*)/g, (m, name) =>
            classes.has(name) ? `.qh-${name}` : m,
          ),
        )
        .map((one) => (one.startsWith(":") ? `.qh ${one}` : `.qh ${one}`))
        .join(", ");
      return `  ${scoped} {${body.trim()}}`;
    })
    .filter(Boolean)
    .join("\n");
}

/* ----------------------------------------------------------------- HTML */

function transformHtml(html, classes) {
  let out = html;

  // The chat page's own hero and footer are dropped: the article has both.
  out = out.slice(out.indexOf("</header>") + "</header>".length, out.indexOf("<footer>"));

  // Rename the classes the stylesheet renamed, inside SVG markup as well.
  out = out.replace(/class="([^"]*)"/g, (whole, value) => {
    const renamed = value
      .split(/\s+/)
      .filter(Boolean)
      .map((name) => (classes.has(name) ? `qh-${name}` : name))
      .join(" ");
    return `class="${renamed}"`;
  });

  // Rebuild each section in the article's own shape: its `section > .wrap`
  // frame, and its `sec-head` with a numbered eyebrow.
  out = out.replace(
    /<section class="qh-sec" id="([a-z]+)"[^>]*>/g,
    (whole, id) => `<section id="quadro-${id}">\n  <div class="wrap qh">`,
  );
  out = out.replace(/<\/section>/g, "  </div>\n</section>");
  out = out.replace(/<div class="qh-sechead">([\s\S]*?)<\/div>/g, (whole, inner, offset) => {
    const id = [...out.slice(0, offset).matchAll(/<section id="quadro-([a-z]+)">/g)].pop()?.[1];
    const eyebrow = EYEBROWS[id];
    if (!eyebrow) throw new Error(`no eyebrow for section ${id}`);
    return `<div class="sec-head"><p class="eyebrow">${eyebrow}</p>${inner.trim()}</div>`;
  });

  return out.trim();
}

/* ----------------------------------------------------------------- main */

const source = readFileSync(SOURCE, "utf8");
const styleMatch = source.match(/<style>([\s\S]*?)<\/style>/);
if (!styleMatch) throw new Error(`${SOURCE}: no <style> block`);

const classes = classNames(styleMatch[1]);
// `wrap` is the article's own container, kept as-is on the section wrappers.
classes.delete("wrap");

const palette = `  .qh {
    /* The chat page's palette, remapped onto the article's. Its pitch green
       becomes the francesinha orange, and its second series the chart green
       already validated against this surface. */
    --bg: var(--ground);
    --surface: #131C22;
    --surface2: #1C262E;
    --sunk: #0D141A;
    --ink: #ECE5D8;
    --ink2: #A9B7C0;
    --muted: #5E6E79;
    --line: #2A3841;
    --pitch: var(--bad);
    --pitch-ink: var(--bad);
    --pitch-soft: var(--sauce-dim);
    --yellow: #E0B040;
    --red: var(--reject);
    --s2: var(--good);
    --shadow: 0 1px 2px rgba(0, 0, 0, 0.4);
    font-size: 1rem;
  }

  /* A grid item's default \`min-width: auto\` lets the 520px minimum on the
     charts and tables push the whole page sideways on a phone. */
  .qh .qh-charts > *, .qh .qh-chartscroll, .qh .qh-grid2 > *, .qh .qh-awards > * {
    min-width: 0;
  }

  /* Tables in the two halves should read as the same publication: display
     face in the header, body face on the names, mono on the numbers. */
  .qh thead th { font-family: var(--display); letter-spacing: 0.1em; font-weight: 600; }
  .qh .qh-nm { font-family: var(--body); font-size: 0.95rem; font-weight: 400; }`;

const css = transformCss(styleMatch[1], classes)
  // Two display faces become the article's two.
  .replace(/"Bebas Neue", ?(?:Impact, ?)?sans-serif/g, "var(--display)")
  .replace(/"Source Serif 4", ?Georgia, ?serif/g, "var(--body)")
  .replace(/"IBM Plex Mono", ?(?:ui-monospace, ?Menlo, ?)?monospace/g, "var(--mono)");

const html = transformHtml(source, classes);

let article = readFileSync(ARTICLE, "utf8");

const cssBlock = `${CSS_OPEN}\n${palette}\n${css}\n${CSS_CLOSE}\n`;
if (article.includes(CSS_OPEN)) {
  const from = article.indexOf(CSS_OPEN);
  const to = article.indexOf(CSS_CLOSE) + CSS_CLOSE.length + 1;
  article = article.slice(0, from) + cssBlock + article.slice(to);
} else {
  const close = article.indexOf("</style>");
  article = article.slice(0, close) + cssBlock + article.slice(close);
}

const htmlBlock = `${HTML_OPEN}\n${html}\n${HTML_CLOSE}\n\n`;
if (article.includes(HTML_OPEN)) {
  const from = article.indexOf(HTML_OPEN);
  const to = article.indexOf(HTML_CLOSE) + HTML_CLOSE.length + 2;
  article = article.slice(0, from) + htmlBlock + article.slice(to);
} else {
  const footer = article.lastIndexOf("<footer>");
  article = article.slice(0, footer) + htmlBlock + article.slice(footer);
}

writeFileSync(ARTICLE, article);
console.log(
  `articles/ficheiros-da-francesinha.html  +${html.split("\n").length} lines of markup, ${css.split("\n").length} of CSS`,
);
