/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlayersRouteImport } from './routes/players'
import { Route as LeaguesRouteImport } from './routes/leagues'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GameIdRouteImport } from './routes/game/$id'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLogoutRouteImport } from './routes/auth/logout'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as CreateGameIndexRouteImport } from './routes/create/game/index'
import { Route as PlayerGames_playedPlayerNameRouteImport } from './routes/player/games_played/$playerName'
import { Route as PlayerAll_editionsPlayerNameRouteImport } from './routes/player/all_editions/$playerName'
import { Route as CreateGameEditionNameRouteImport } from './routes/create/game/$editionName'
import { Route as CreateChoose_editionViewRouteImport } from './routes/create/choose_edition/$view'
import { Route as ScoresTableLeagueIdIndexRouteImport } from './routes/scores/table/$leagueId/index'
import { Route as ScoresScorersLeagueIdIndexRouteImport } from './routes/scores/scorers/$leagueId/index'
import { Route as ScoresGamesLeagueIdIndexRouteImport } from './routes/scores/games/$leagueId/index'
import { Route as ScoresCreate_teamsLeagueIdIndexRouteImport } from './routes/scores/create_teams/$leagueId/index'
import { Route as PlayerGeneralPlayerNameIndexRouteImport } from './routes/player/general/$playerName/index'
import { Route as ScoresScorersLeagueIdEditionIdRouteImport } from './routes/scores/scorers/$leagueId/$editionId'
import { Route as ScoresGamesLeagueIdEditionIdRouteImport } from './routes/scores/games/$leagueId/$editionId'
import { Route as ScoresCreate_teamsLeagueIdEditionIdRouteImport } from './routes/scores/create_teams/$leagueId/$editionId'
import { Route as PlayerGeneralPlayerNameEditionNameRouteImport } from './routes/player/general/$playerName/$editionName'
import { Route as ScoresTableLeagueIdEditionIdIndexRouteImport } from './routes/scores/table/$leagueId/$editionId/index'
import { Route as ScoresTableLeagueIdEditionIdRecalculateRouteImport } from './routes/scores/table/$leagueId/$editionId/$recalculate'

const PlayersRoute = PlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaguesRoute = LeaguesRouteImport.update({
  id: '/leagues',
  path: '/leagues',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameIdRoute = GameIdRouteImport.update({
  id: '/game/$id',
  path: '/game/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateGameIndexRoute = CreateGameIndexRouteImport.update({
  id: '/create/game/',
  path: '/create/game/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerGames_playedPlayerNameRoute =
  PlayerGames_playedPlayerNameRouteImport.update({
    id: '/player/games_played/$playerName',
    path: '/player/games_played/$playerName',
    getParentRoute: () => rootRouteImport,
  } as any)
const PlayerAll_editionsPlayerNameRoute =
  PlayerAll_editionsPlayerNameRouteImport.update({
    id: '/player/all_editions/$playerName',
    path: '/player/all_editions/$playerName',
    getParentRoute: () => rootRouteImport,
  } as any)
const CreateGameEditionNameRoute = CreateGameEditionNameRouteImport.update({
  id: '/create/game/$editionName',
  path: '/create/game/$editionName',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateChoose_editionViewRoute =
  CreateChoose_editionViewRouteImport.update({
    id: '/create/choose_edition/$view',
    path: '/create/choose_edition/$view',
    getParentRoute: () => rootRouteImport,
  } as any)
const ScoresTableLeagueIdIndexRoute =
  ScoresTableLeagueIdIndexRouteImport.update({
    id: '/scores/table/$leagueId/',
    path: '/scores/table/$leagueId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ScoresScorersLeagueIdIndexRoute =
  ScoresScorersLeagueIdIndexRouteImport.update({
    id: '/scores/scorers/$leagueId/',
    path: '/scores/scorers/$leagueId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ScoresGamesLeagueIdIndexRoute =
  ScoresGamesLeagueIdIndexRouteImport.update({
    id: '/scores/games/$leagueId/',
    path: '/scores/games/$leagueId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ScoresCreate_teamsLeagueIdIndexRoute =
  ScoresCreate_teamsLeagueIdIndexRouteImport.update({
    id: '/scores/create_teams/$leagueId/',
    path: '/scores/create_teams/$leagueId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PlayerGeneralPlayerNameIndexRoute =
  PlayerGeneralPlayerNameIndexRouteImport.update({
    id: '/player/general/$playerName/',
    path: '/player/general/$playerName/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ScoresScorersLeagueIdEditionIdRoute =
  ScoresScorersLeagueIdEditionIdRouteImport.update({
    id: '/scores/scorers/$leagueId/$editionId',
    path: '/scores/scorers/$leagueId/$editionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ScoresGamesLeagueIdEditionIdRoute =
  ScoresGamesLeagueIdEditionIdRouteImport.update({
    id: '/scores/games/$leagueId/$editionId',
    path: '/scores/games/$leagueId/$editionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ScoresCreate_teamsLeagueIdEditionIdRoute =
  ScoresCreate_teamsLeagueIdEditionIdRouteImport.update({
    id: '/scores/create_teams/$leagueId/$editionId',
    path: '/scores/create_teams/$leagueId/$editionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const PlayerGeneralPlayerNameEditionNameRoute =
  PlayerGeneralPlayerNameEditionNameRouteImport.update({
    id: '/player/general/$playerName/$editionName',
    path: '/player/general/$playerName/$editionName',
    getParentRoute: () => rootRouteImport,
  } as any)
const ScoresTableLeagueIdEditionIdIndexRoute =
  ScoresTableLeagueIdEditionIdIndexRouteImport.update({
    id: '/scores/table/$leagueId/$editionId/',
    path: '/scores/table/$leagueId/$editionId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ScoresTableLeagueIdEditionIdRecalculateRoute =
  ScoresTableLeagueIdEditionIdRecalculateRouteImport.update({
    id: '/scores/table/$leagueId/$editionId/$recalculate',
    path: '/scores/table/$leagueId/$editionId/$recalculate',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/leagues': typeof LeaguesRoute
  '/players': typeof PlayersRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/register': typeof AuthRegisterRoute
  '/game/$id': typeof GameIdRoute
  '/create/choose_edition/$view': typeof CreateChoose_editionViewRoute
  '/create/game/$editionName': typeof CreateGameEditionNameRoute
  '/player/all_editions/$playerName': typeof PlayerAll_editionsPlayerNameRoute
  '/player/games_played/$playerName': typeof PlayerGames_playedPlayerNameRoute
  '/create/game/': typeof CreateGameIndexRoute
  '/player/general/$playerName/$editionName': typeof PlayerGeneralPlayerNameEditionNameRoute
  '/scores/create_teams/$leagueId/$editionId': typeof ScoresCreate_teamsLeagueIdEditionIdRoute
  '/scores/games/$leagueId/$editionId': typeof ScoresGamesLeagueIdEditionIdRoute
  '/scores/scorers/$leagueId/$editionId': typeof ScoresScorersLeagueIdEditionIdRoute
  '/player/general/$playerName/': typeof PlayerGeneralPlayerNameIndexRoute
  '/scores/create_teams/$leagueId/': typeof ScoresCreate_teamsLeagueIdIndexRoute
  '/scores/games/$leagueId/': typeof ScoresGamesLeagueIdIndexRoute
  '/scores/scorers/$leagueId/': typeof ScoresScorersLeagueIdIndexRoute
  '/scores/table/$leagueId/': typeof ScoresTableLeagueIdIndexRoute
  '/scores/table/$leagueId/$editionId/$recalculate': typeof ScoresTableLeagueIdEditionIdRecalculateRoute
  '/scores/table/$leagueId/$editionId/': typeof ScoresTableLeagueIdEditionIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/leagues': typeof LeaguesRoute
  '/players': typeof PlayersRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/register': typeof AuthRegisterRoute
  '/game/$id': typeof GameIdRoute
  '/create/choose_edition/$view': typeof CreateChoose_editionViewRoute
  '/create/game/$editionName': typeof CreateGameEditionNameRoute
  '/player/all_editions/$playerName': typeof PlayerAll_editionsPlayerNameRoute
  '/player/games_played/$playerName': typeof PlayerGames_playedPlayerNameRoute
  '/create/game': typeof CreateGameIndexRoute
  '/player/general/$playerName/$editionName': typeof PlayerGeneralPlayerNameEditionNameRoute
  '/scores/create_teams/$leagueId/$editionId': typeof ScoresCreate_teamsLeagueIdEditionIdRoute
  '/scores/games/$leagueId/$editionId': typeof ScoresGamesLeagueIdEditionIdRoute
  '/scores/scorers/$leagueId/$editionId': typeof ScoresScorersLeagueIdEditionIdRoute
  '/player/general/$playerName': typeof PlayerGeneralPlayerNameIndexRoute
  '/scores/create_teams/$leagueId': typeof ScoresCreate_teamsLeagueIdIndexRoute
  '/scores/games/$leagueId': typeof ScoresGamesLeagueIdIndexRoute
  '/scores/scorers/$leagueId': typeof ScoresScorersLeagueIdIndexRoute
  '/scores/table/$leagueId': typeof ScoresTableLeagueIdIndexRoute
  '/scores/table/$leagueId/$editionId/$recalculate': typeof ScoresTableLeagueIdEditionIdRecalculateRoute
  '/scores/table/$leagueId/$editionId': typeof ScoresTableLeagueIdEditionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/leagues': typeof LeaguesRoute
  '/players': typeof PlayersRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/register': typeof AuthRegisterRoute
  '/game/$id': typeof GameIdRoute
  '/create/choose_edition/$view': typeof CreateChoose_editionViewRoute
  '/create/game/$editionName': typeof CreateGameEditionNameRoute
  '/player/all_editions/$playerName': typeof PlayerAll_editionsPlayerNameRoute
  '/player/games_played/$playerName': typeof PlayerGames_playedPlayerNameRoute
  '/create/game/': typeof CreateGameIndexRoute
  '/player/general/$playerName/$editionName': typeof PlayerGeneralPlayerNameEditionNameRoute
  '/scores/create_teams/$leagueId/$editionId': typeof ScoresCreate_teamsLeagueIdEditionIdRoute
  '/scores/games/$leagueId/$editionId': typeof ScoresGamesLeagueIdEditionIdRoute
  '/scores/scorers/$leagueId/$editionId': typeof ScoresScorersLeagueIdEditionIdRoute
  '/player/general/$playerName/': typeof PlayerGeneralPlayerNameIndexRoute
  '/scores/create_teams/$leagueId/': typeof ScoresCreate_teamsLeagueIdIndexRoute
  '/scores/games/$leagueId/': typeof ScoresGamesLeagueIdIndexRoute
  '/scores/scorers/$leagueId/': typeof ScoresScorersLeagueIdIndexRoute
  '/scores/table/$leagueId/': typeof ScoresTableLeagueIdIndexRoute
  '/scores/table/$leagueId/$editionId/$recalculate': typeof ScoresTableLeagueIdEditionIdRecalculateRoute
  '/scores/table/$leagueId/$editionId/': typeof ScoresTableLeagueIdEditionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/leagues'
    | '/players'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/register'
    | '/game/$id'
    | '/create/choose_edition/$view'
    | '/create/game/$editionName'
    | '/player/all_editions/$playerName'
    | '/player/games_played/$playerName'
    | '/create/game/'
    | '/player/general/$playerName/$editionName'
    | '/scores/create_teams/$leagueId/$editionId'
    | '/scores/games/$leagueId/$editionId'
    | '/scores/scorers/$leagueId/$editionId'
    | '/player/general/$playerName/'
    | '/scores/create_teams/$leagueId/'
    | '/scores/games/$leagueId/'
    | '/scores/scorers/$leagueId/'
    | '/scores/table/$leagueId/'
    | '/scores/table/$leagueId/$editionId/$recalculate'
    | '/scores/table/$leagueId/$editionId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/leagues'
    | '/players'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/register'
    | '/game/$id'
    | '/create/choose_edition/$view'
    | '/create/game/$editionName'
    | '/player/all_editions/$playerName'
    | '/player/games_played/$playerName'
    | '/create/game'
    | '/player/general/$playerName/$editionName'
    | '/scores/create_teams/$leagueId/$editionId'
    | '/scores/games/$leagueId/$editionId'
    | '/scores/scorers/$leagueId/$editionId'
    | '/player/general/$playerName'
    | '/scores/create_teams/$leagueId'
    | '/scores/games/$leagueId'
    | '/scores/scorers/$leagueId'
    | '/scores/table/$leagueId'
    | '/scores/table/$leagueId/$editionId/$recalculate'
    | '/scores/table/$leagueId/$editionId'
  id:
    | '__root__'
    | '/'
    | '/leagues'
    | '/players'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/register'
    | '/game/$id'
    | '/create/choose_edition/$view'
    | '/create/game/$editionName'
    | '/player/all_editions/$playerName'
    | '/player/games_played/$playerName'
    | '/create/game/'
    | '/player/general/$playerName/$editionName'
    | '/scores/create_teams/$leagueId/$editionId'
    | '/scores/games/$leagueId/$editionId'
    | '/scores/scorers/$leagueId/$editionId'
    | '/player/general/$playerName/'
    | '/scores/create_teams/$leagueId/'
    | '/scores/games/$leagueId/'
    | '/scores/scorers/$leagueId/'
    | '/scores/table/$leagueId/'
    | '/scores/table/$leagueId/$editionId/$recalculate'
    | '/scores/table/$leagueId/$editionId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LeaguesRoute: typeof LeaguesRoute
  PlayersRoute: typeof PlayersRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  GameIdRoute: typeof GameIdRoute
  CreateChoose_editionViewRoute: typeof CreateChoose_editionViewRoute
  CreateGameEditionNameRoute: typeof CreateGameEditionNameRoute
  PlayerAll_editionsPlayerNameRoute: typeof PlayerAll_editionsPlayerNameRoute
  PlayerGames_playedPlayerNameRoute: typeof PlayerGames_playedPlayerNameRoute
  CreateGameIndexRoute: typeof CreateGameIndexRoute
  PlayerGeneralPlayerNameEditionNameRoute: typeof PlayerGeneralPlayerNameEditionNameRoute
  ScoresCreate_teamsLeagueIdEditionIdRoute: typeof ScoresCreate_teamsLeagueIdEditionIdRoute
  ScoresGamesLeagueIdEditionIdRoute: typeof ScoresGamesLeagueIdEditionIdRoute
  ScoresScorersLeagueIdEditionIdRoute: typeof ScoresScorersLeagueIdEditionIdRoute
  PlayerGeneralPlayerNameIndexRoute: typeof PlayerGeneralPlayerNameIndexRoute
  ScoresCreate_teamsLeagueIdIndexRoute: typeof ScoresCreate_teamsLeagueIdIndexRoute
  ScoresGamesLeagueIdIndexRoute: typeof ScoresGamesLeagueIdIndexRoute
  ScoresScorersLeagueIdIndexRoute: typeof ScoresScorersLeagueIdIndexRoute
  ScoresTableLeagueIdIndexRoute: typeof ScoresTableLeagueIdIndexRoute
  ScoresTableLeagueIdEditionIdRecalculateRoute: typeof ScoresTableLeagueIdEditionIdRecalculateRoute
  ScoresTableLeagueIdEditionIdIndexRoute: typeof ScoresTableLeagueIdEditionIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/players': {
      id: '/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof PlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leagues': {
      id: '/leagues'
      path: '/leagues'
      fullPath: '/leagues'
      preLoaderRoute: typeof LeaguesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$id': {
      id: '/game/$id'
      path: '/game/$id'
      fullPath: '/game/$id'
      preLoaderRoute: typeof GameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/game/': {
      id: '/create/game/'
      path: '/create/game'
      fullPath: '/create/game/'
      preLoaderRoute: typeof CreateGameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/games_played/$playerName': {
      id: '/player/games_played/$playerName'
      path: '/player/games_played/$playerName'
      fullPath: '/player/games_played/$playerName'
      preLoaderRoute: typeof PlayerGames_playedPlayerNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/all_editions/$playerName': {
      id: '/player/all_editions/$playerName'
      path: '/player/all_editions/$playerName'
      fullPath: '/player/all_editions/$playerName'
      preLoaderRoute: typeof PlayerAll_editionsPlayerNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/game/$editionName': {
      id: '/create/game/$editionName'
      path: '/create/game/$editionName'
      fullPath: '/create/game/$editionName'
      preLoaderRoute: typeof CreateGameEditionNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/choose_edition/$view': {
      id: '/create/choose_edition/$view'
      path: '/create/choose_edition/$view'
      fullPath: '/create/choose_edition/$view'
      preLoaderRoute: typeof CreateChoose_editionViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scores/table/$leagueId/': {
      id: '/scores/table/$leagueId/'
      path: '/scores/table/$leagueId'
      fullPath: '/scores/table/$leagueId/'
      preLoaderRoute: typeof ScoresTableLeagueIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scores/scorers/$leagueId/': {
      id: '/scores/scorers/$leagueId/'
      path: '/scores/scorers/$leagueId'
      fullPath: '/scores/scorers/$leagueId/'
      preLoaderRoute: typeof ScoresScorersLeagueIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scores/games/$leagueId/': {
      id: '/scores/games/$leagueId/'
      path: '/scores/games/$leagueId'
      fullPath: '/scores/games/$leagueId/'
      preLoaderRoute: typeof ScoresGamesLeagueIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scores/create_teams/$leagueId/': {
      id: '/scores/create_teams/$leagueId/'
      path: '/scores/create_teams/$leagueId'
      fullPath: '/scores/create_teams/$leagueId/'
      preLoaderRoute: typeof ScoresCreate_teamsLeagueIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/general/$playerName/': {
      id: '/player/general/$playerName/'
      path: '/player/general/$playerName'
      fullPath: '/player/general/$playerName/'
      preLoaderRoute: typeof PlayerGeneralPlayerNameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scores/scorers/$leagueId/$editionId': {
      id: '/scores/scorers/$leagueId/$editionId'
      path: '/scores/scorers/$leagueId/$editionId'
      fullPath: '/scores/scorers/$leagueId/$editionId'
      preLoaderRoute: typeof ScoresScorersLeagueIdEditionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scores/games/$leagueId/$editionId': {
      id: '/scores/games/$leagueId/$editionId'
      path: '/scores/games/$leagueId/$editionId'
      fullPath: '/scores/games/$leagueId/$editionId'
      preLoaderRoute: typeof ScoresGamesLeagueIdEditionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scores/create_teams/$leagueId/$editionId': {
      id: '/scores/create_teams/$leagueId/$editionId'
      path: '/scores/create_teams/$leagueId/$editionId'
      fullPath: '/scores/create_teams/$leagueId/$editionId'
      preLoaderRoute: typeof ScoresCreate_teamsLeagueIdEditionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/general/$playerName/$editionName': {
      id: '/player/general/$playerName/$editionName'
      path: '/player/general/$playerName/$editionName'
      fullPath: '/player/general/$playerName/$editionName'
      preLoaderRoute: typeof PlayerGeneralPlayerNameEditionNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scores/table/$leagueId/$editionId/': {
      id: '/scores/table/$leagueId/$editionId/'
      path: '/scores/table/$leagueId/$editionId'
      fullPath: '/scores/table/$leagueId/$editionId/'
      preLoaderRoute: typeof ScoresTableLeagueIdEditionIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scores/table/$leagueId/$editionId/$recalculate': {
      id: '/scores/table/$leagueId/$editionId/$recalculate'
      path: '/scores/table/$leagueId/$editionId/$recalculate'
      fullPath: '/scores/table/$leagueId/$editionId/$recalculate'
      preLoaderRoute: typeof ScoresTableLeagueIdEditionIdRecalculateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LeaguesRoute: LeaguesRoute,
  PlayersRoute: PlayersRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  GameIdRoute: GameIdRoute,
  CreateChoose_editionViewRoute: CreateChoose_editionViewRoute,
  CreateGameEditionNameRoute: CreateGameEditionNameRoute,
  PlayerAll_editionsPlayerNameRoute: PlayerAll_editionsPlayerNameRoute,
  PlayerGames_playedPlayerNameRoute: PlayerGames_playedPlayerNameRoute,
  CreateGameIndexRoute: CreateGameIndexRoute,
  PlayerGeneralPlayerNameEditionNameRoute:
    PlayerGeneralPlayerNameEditionNameRoute,
  ScoresCreate_teamsLeagueIdEditionIdRoute:
    ScoresCreate_teamsLeagueIdEditionIdRoute,
  ScoresGamesLeagueIdEditionIdRoute: ScoresGamesLeagueIdEditionIdRoute,
  ScoresScorersLeagueIdEditionIdRoute: ScoresScorersLeagueIdEditionIdRoute,
  PlayerGeneralPlayerNameIndexRoute: PlayerGeneralPlayerNameIndexRoute,
  ScoresCreate_teamsLeagueIdIndexRoute: ScoresCreate_teamsLeagueIdIndexRoute,
  ScoresGamesLeagueIdIndexRoute: ScoresGamesLeagueIdIndexRoute,
  ScoresScorersLeagueIdIndexRoute: ScoresScorersLeagueIdIndexRoute,
  ScoresTableLeagueIdIndexRoute: ScoresTableLeagueIdIndexRoute,
  ScoresTableLeagueIdEditionIdRecalculateRoute:
    ScoresTableLeagueIdEditionIdRecalculateRoute,
  ScoresTableLeagueIdEditionIdIndexRoute:
    ScoresTableLeagueIdEditionIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
